// <auto-generated />
using System;
using Deanery.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deanery.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623200152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Deanery.Data.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Teacher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Программирование",
                            Semester = 3,
                            Teacher = "Смирнов А.В.",
                            TotalHours = 120
                        },
                        new
                        {
                            Id = 2,
                            Name = "Базы данных",
                            Semester = 3,
                            Teacher = "Кузнецова Е.Н.",
                            TotalHours = 90
                        },
                        new
                        {
                            Id = 3,
                            Name = "Математика",
                            Semester = 1,
                            Teacher = "Попов И.Л.",
                            TotalHours = 144
                        },
                        new
                        {
                            Id = 4,
                            Name = "Сети и телекоммуникации",
                            Semester = 4,
                            Teacher = "Волков Д.С.",
                            TotalHours = 72
                        },
                        new
                        {
                            Id = 5,
                            Name = "Информационная безопасность",
                            Semester = 5,
                            Teacher = "Лебедева О.М.",
                            TotalHours = 54
                        });
                });

            modelBuilder.Entity("Deanery.Data.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineId = 1,
                            Score = 5,
                            StudentId = 1,
                            WorkType = "Экзамен"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineId = 2,
                            Score = 4,
                            StudentId = 1,
                            WorkType = "Контрольная"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineId = 1,
                            Score = 4,
                            StudentId = 2,
                            WorkType = "Экзамен"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineId = 3,
                            Score = 2,
                            StudentId = 2,
                            WorkType = "Экзамен"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineId = 4,
                            Score = 3,
                            StudentId = 3,
                            WorkType = "Лабораторная"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineId = 2,
                            Score = 5,
                            StudentId = 4,
                            WorkType = "Курсовая"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineId = 1,
                            Score = 2,
                            StudentId = 5,
                            WorkType = "Контрольная"
                        });
                });

            modelBuilder.Entity("Deanery.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Пётр",
                            GroupName = "ИС-21",
                            LastName = "Иванов",
                            MiddleName = "Сергеевич",
                            Phone = "+7 (900) 111-11-11",
                            Status = "Обучается"
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Анна",
                            GroupName = "ИС-21",
                            LastName = "Петрова",
                            MiddleName = "Игоревна",
                            Phone = "+7 (900) 222-22-22",
                            Status = "Обучается"
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Олег",
                            GroupName = "ИС-22",
                            LastName = "Сидоров",
                            MiddleName = "Андреевич",
                            Phone = "+7 (900) 333-33-33",
                            Status = "Обучается"
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Мария",
                            GroupName = "ИС-22",
                            LastName = "Козлова",
                            MiddleName = "Павловна",
                            Phone = "+7 (900) 444-44-44",
                            Status = "Обучается"
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Дмитрий",
                            GroupName = "ИС-21",
                            LastName = "Новиков",
                            MiddleName = "Викторович",
                            Phone = "+7 (900) 555-55-55",
                            Status = "Академ"
                        });
                });

            modelBuilder.Entity("Deanery.Data.Models.Grade", b =>
                {
                    b.HasOne("Deanery.Data.Models.Discipline", "Discipline")
                        .WithMany("Grades")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Deanery.Data.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Deanery.Data.Models.Discipline", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Deanery.Data.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
